name: Terraform Provider ACI Checks

on:
  pull_request:
    paths:
      - '.github/workflows/test.yaml'
      - '**.go'

permissions:
  # Permission for checking out code
  contents: read

jobs:
  format:
    name: Terraform Provider ACI Format Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - run: |
          chmod +x ./scripts/gofmtcheck.sh
          ./scripts/gofmtcheck.sh
  acceptance:
    name: Terraform Provider ACI Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.*'
          terraform_wrapper: false
      - run: go test github.com/CiscoDevNet/terraform-provider-aci/v2/internal/provider -v -cover -timeout 120m
        env:
          TF_ACC: '1'
          TF_ACC_STATE_LINEAGE: '1'
          ACI_USERNAME: ${{ secrets.TF_ACC_ACI_USERNAME }}
          ACI_PASSWORD: ${{ secrets.TF_ACC_ACI_PASSWORD }}
          ACI_URL: ${{ secrets.TF_ACC_ACI_URL }}